### ISSUE TITLE
Building malt (or perhaps just malt-webview) on Mac OS X? 

### ISSUE THREAD

**Issue by gshipman** [memtt/malt#61]
Looks like there are dependencies on pthread that is not on OS X.  I took a look at `-DPORTABILITY_OS={UNIX}` and `-DPORTABILITY_MUTEX={PTHREAD}` but I didn't see support for OS X. If OS X isn't supported by malt, is it possible to only build malt-webview? I can then use my Mac to visualize results. 

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=malt/release
```

```
[  4%] Building CXX object src/lib/core/CMakeFiles/malt-core.dir/VmaTracker.cpp.o
In file included from malt/src/lib/core/VmaTracker.cpp:14:
In file included from malt/src/lib/./common/SimpleAllocator.hpp:17:
In file included from malt/src/lib/./portability/Spinlock.hpp:19:
malt/src/lib/./portability/SpinlockPthread.hpp:29:3: error: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
                pthread_spinlock_t spinlock;
                ^~~~~~~~~~~~~~~~~~
                pthread_rwlock_t
```

**Comment by svalat** [comment]
Hi,
A quick answer before I look in more details:

1. About the spinlock: yes pthread_spinlock_t is not provided under macosx. I have an equivalent here which can be imported in MALT with a bit of work: https://gitlab.cern.ch/lhcb-online-eb/lhcb-daqpipe-v2/-/blob/master/src/portability/SpinlockPthread.hpp. I don't know if it is still supported by recent macrosx. Another solution a bit less performance is to replace them by pthread mutex.
2. I think there are some other points which might lead to issues on macosx. It would be nice if you can confirm to me. Mostly there might be an issue because I use some files in /proc (/proc/self/maps, /proc/meminfo, /proc/self/statm, /proc/self/exe). Are they available on osx ?
3. About installing only the view, yes you can install it alone by commenting the `add_subdirectory()` commands in https://github.com/memtt/malt/blob/master/src/CMakeLists.txt. Maybe I can think adding an option for this, that's a good remark.

**Comment by gshipman** [comment]
Thanks much for the quick response. The viewer is really all I need for my use case. I was able to get this working without installing, simply going into the src dir and running: 
`node malt-webserver.js --no-auth  -i <file>`

That has gotten me moving with analysis. I might be able to get a merge in for modifying the build to add this as an option.

**Comment by svalat** [comment]
As proposed I added a `--disable-profiler` to be able to install only the GUI.

I let the port of the profiler lib to MacOSX for another dedicated issue (#64), can close this one.
