### ISSUE TITLE
Introduce CI in github action to validate patches

### ISSUE THREAD

**Issue by svalat** [memtt/malt#90]
Need to run the tests in CI.

**Comment by bernarda78** [comment]
Hi,

It seems to me that this issue is already resolved by commits 7947a0e5092842a4323bdbb8cfc792e4411b3aa4, 837c5b796bebb2aef62481104fa0d3b6f43612b6 and c944b11392cffb1f5511f3c3dfa9563612fea6e4.

In addition:
 + `ctest` is used to call the test whereas `make test` is described in the [README.md](https://github.com/memtt/malt/blob/master/README.md), but this is only cosmetic.
 + if you've totally moved to Github Actions for CI/CD, the file [.gitlab-ci.yml](https://github.com/memtt/malt/blob/master/.gitlab-ci.yml) is useless. If so, maybe remove it ?

**Comment by svalat** [comment]
Thanks for looking that.

True, that's already fixed.

- I would keep the gitlab file for people developing under gitlab (me sometime).

**Comment by svalat** [comment]
Already done by : 
- 7947a0e5092842a4323bdbb8cfc792e4411b3aa4
- 837c5b796bebb2aef62481104fa0d3b6f43612b6
- c944b11392cffb1f5511f3c3dfa9563612fea6e4.
